using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Item : MonoBehaviour
{
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    //ÚG‚µ‚½uŠÔŒÄ‚Î‚ê‚é
    private void OnTriggerEnter(Collider other)
    {
        //ÚG‚µ‚½‚çÁ–Å
        DestroySelf();
        //Debug.Log("Enter");
    }

    private void DestroySelf()
    {
        Destroy(gameObject);
    }

    //ÚG‚µ‚Ä‚¢‚éŠÔ‚ÉŒÄ‚Î‚ê‚é
    private void OnTriggerStay(Collider other)
    {
        Debug.Log("Stay");
    }

    //—£‚ê‚½‚Æ‚«‚ÉŒÄ‚Î‚ê‚é
    private void OnTriggerExit(Collider other)
    {
        Debug.Log("Exit");
    }
}
